# Generated by Django 2.2.3 on 2020-04-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200409_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='age',
            field=models.IntegerField(default=15, null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='choice_of_berth',
            field=models.CharField(choices=[('Lower', 'lower'), ('Middle', 'middle'), ('Upper', 'upper')], default='lower', max_length=10, null=True, verbose_name='choice_of_berth'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gender',
            field=models.CharField(max_length=15, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='journey_date',
            field=models.DateField(null=True, verbose_name='journey_date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='nationality',
            field=models.CharField(max_length=20, verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to',
            field=models.CharField(max_length=20, verbose_name='to'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='train_name',
            field=models.CharField(max_length=20, verbose_name='train_name'),
        ),
    ]
