# Generated by Django 2.2.3 on 2020-04-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200409_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='username',
            field=models.CharField(max_length=30, null=True, verbose_name='username'),
        ),
    ]
