# Generated by Django 2.2.3 on 2020-04-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200409_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='journey_date',
            field=models.DateField(null=True, verbose_name='journey_date'),
        ),
    ]
