# Generated by Django 2.2.3 on 2020-04-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200409_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking',
            new_name='bookings',
        ),
    ]
