# Generated by Django 2.2.3 on 2020-04-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200409_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_details',
            name='confirm',
        ),
        migrations.AddField(
            model_name='payment_details',
            name='cvv',
            field=models.CharField(max_length=5, null=True, verbose_name='cvv'),
        ),
    ]
